version: '3.9'

services:
  backend:
    build: ./backend
    container_name: travel_blog_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/db:/usr/src/app/db
    environment:
      - NODE_ENV=development
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: travel_blog_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
